workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 60
    environment:
      vars:
        APIFOOTBALL_KEY: $APIFOOTBALL_KEY
    triggering:
      events:
        - push
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK (release)
        script: flutter build apk --release -t lib/main_production.dart --dart-define=APIFOOTBALL_KEY=$APIFOOTBALL_KEY
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
